-- =============================================
-- V1__baseline.sql
-- Flyway baseline migration
-- 對應所有 JPA Entity 定義，建立完整 schema
-- =============================================
-- 命名規則：索引名稱在 PostgreSQL 中是 schema 級別唯一的，
-- 因此所有索引都帶表名前綴以避免衝突。

-- ==================== 1. users ====================
CREATE TABLE IF NOT EXISTS users (
    user_id             VARCHAR(255)    NOT NULL,
    email               VARCHAR(255)    NOT NULL,
    password_hash       VARCHAR(255)    NOT NULL,
    name                VARCHAR(255),
    role                VARCHAR(255)    DEFAULT 'USER',
    enabled             BOOLEAN         DEFAULT true     NOT NULL,
    auto_trade_enabled  BOOLEAN         DEFAULT true     NOT NULL,
    created_at          TIMESTAMP,
    updated_at          TIMESTAMP,
    CONSTRAINT pk_users PRIMARY KEY (user_id),
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_users_email ON users (email);


-- ==================== 2. trades ====================
CREATE TABLE IF NOT EXISTS trades (
    trade_id                VARCHAR(255)    NOT NULL,
    user_id                 VARCHAR(255),
    symbol                  VARCHAR(255),
    side                    VARCHAR(255),
    entry_price             DOUBLE PRECISION,
    entry_quantity          DOUBLE PRECISION,
    entry_time              TIMESTAMP,
    entry_order_id          VARCHAR(255),
    exit_price              DOUBLE PRECISION,
    exit_quantity           DOUBLE PRECISION,
    exit_time               TIMESTAMP,
    exit_order_id           VARCHAR(255),
    stop_loss               DOUBLE PRECISION,
    leverage                INTEGER,
    risk_amount             DOUBLE PRECISION,
    gross_profit            DOUBLE PRECISION,
    entry_commission        DOUBLE PRECISION,
    commission              DOUBLE PRECISION,
    net_profit              DOUBLE PRECISION,
    status                  VARCHAR(255),
    exit_reason             VARCHAR(255),
    remaining_quantity      DOUBLE PRECISION,
    total_closed_quantity   DOUBLE PRECISION,
    dca_count               INTEGER,
    signal_hash             VARCHAR(255),
    source_platform         VARCHAR(255),
    source_channel_id       VARCHAR(255),
    source_guild_id         VARCHAR(255),
    source_author_name      VARCHAR(255),
    source_message_id       VARCHAR(255),
    created_at              TIMESTAMP,
    updated_at              TIMESTAMP,
    CONSTRAINT pk_trades PRIMARY KEY (trade_id)
);

CREATE INDEX IF NOT EXISTS idx_trades_user_id ON trades (user_id);
CREATE INDEX IF NOT EXISTS idx_trades_user_symbol ON trades (user_id, symbol);
CREATE INDEX IF NOT EXISTS idx_trades_user_status ON trades (user_id, status);


-- ==================== 3. trade_events ====================
CREATE TABLE IF NOT EXISTS trade_events (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    trade_id            VARCHAR(255),
    event_type          VARCHAR(255),
    timestamp           TIMESTAMP,
    binance_order_id    VARCHAR(255),
    order_side          VARCHAR(255),
    order_type          VARCHAR(255),
    price               DOUBLE PRECISION,
    quantity            DOUBLE PRECISION,
    success             BOOLEAN,
    error_message       VARCHAR(255),
    detail              VARCHAR(2000),
    CONSTRAINT pk_trade_events PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_te_trade_id ON trade_events (trade_id);
CREATE INDEX IF NOT EXISTS idx_te_event_type ON trade_events (event_type);
CREATE INDEX IF NOT EXISTS idx_te_timestamp ON trade_events (timestamp);


-- ==================== 4. user_api_keys ====================
CREATE TABLE IF NOT EXISTS user_api_keys (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id                 VARCHAR(255)    NOT NULL,
    exchange                VARCHAR(255)    DEFAULT 'BINANCE',
    encrypted_api_key       VARCHAR(512),
    encrypted_secret_key    VARCHAR(512),
    created_at              TIMESTAMP,
    updated_at              TIMESTAMP,
    CONSTRAINT pk_user_api_keys PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_uak_user_id ON user_api_keys (user_id);


-- ==================== 5. user_discord_webhooks ====================
CREATE TABLE IF NOT EXISTS user_discord_webhooks (
    webhook_id      VARCHAR(255)    NOT NULL,
    user_id         VARCHAR(255)    NOT NULL,
    webhook_url     VARCHAR(255)    NOT NULL,
    enabled         BOOLEAN         DEFAULT true     NOT NULL,
    name            VARCHAR(255),
    created_at      TIMESTAMP,
    updated_at      TIMESTAMP,
    CONSTRAINT pk_user_discord_webhooks PRIMARY KEY (webhook_id)
);

CREATE INDEX IF NOT EXISTS idx_udw_user_id ON user_discord_webhooks (user_id);


-- ==================== 6. subscriptions ====================
CREATE TABLE IF NOT EXISTS subscriptions (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id                     VARCHAR(255)    NOT NULL,
    stripe_customer_id          VARCHAR(255),
    stripe_subscription_id      VARCHAR(255),
    plan_id                     VARCHAR(255),
    status                      VARCHAR(255)    DEFAULT 'TRIALING',
    current_period_start        TIMESTAMP,
    current_period_end          TIMESTAMP,
    created_at                  TIMESTAMP,
    updated_at                  TIMESTAMP,
    CONSTRAINT pk_subscriptions PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_sub_user_id ON subscriptions (user_id);
CREATE INDEX IF NOT EXISTS idx_sub_stripe_id ON subscriptions (stripe_subscription_id);


-- ==================== 7. audit_logs ====================
CREATE TABLE IF NOT EXISTS audit_logs (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id         VARCHAR(36),
    action          VARCHAR(50)     NOT NULL,
    resource        VARCHAR(200),
    status          VARCHAR(20)     NOT NULL,
    ip_address      VARCHAR(45),
    timestamp       TIMESTAMP       NOT NULL,
    details         TEXT,
    CONSTRAINT pk_audit_logs PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_al_user_id ON audit_logs (user_id);
CREATE INDEX IF NOT EXISTS idx_al_timestamp ON audit_logs (timestamp);
CREATE INDEX IF NOT EXISTS idx_al_action ON audit_logs (action);
CREATE INDEX IF NOT EXISTS idx_al_status ON audit_logs (status);
