-- =============================================
-- V4: plans + payment_history + user_trade_settings + signals
-- =============================================

-- 1. plans — 訂閱方案定義
CREATE TABLE IF NOT EXISTS plans (
    plan_id                     VARCHAR(255)        NOT NULL,
    name                        VARCHAR(255)        NOT NULL,
    price_monthly               DOUBLE PRECISION,
    price_yearly                DOUBLE PRECISION,
    max_positions               INTEGER,
    max_symbols                 INTEGER,
    max_risk_percent            DOUBLE PRECISION,
    dca_layers_allowed          INTEGER,
    features                    TEXT,
    active                      BOOLEAN             DEFAULT true NOT NULL,
    created_at                  TIMESTAMP,
    updated_at                  TIMESTAMP,
    CONSTRAINT pk_plans PRIMARY KEY (plan_id)
);

CREATE INDEX IF NOT EXISTS idx_plans_active ON plans (active);

-- Seed data
INSERT INTO plans (plan_id, name, price_monthly, price_yearly, max_positions, max_symbols, max_risk_percent, dca_layers_allowed, features, active, created_at, updated_at)
VALUES
    ('free',  'Free',  0,     0,   1,  3,  0.10, 0,  '{}', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('basic', 'Basic', 9.99,  99,  5,  10, 0.20, 3,  '{"discord_webhook": true}', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('pro',   'Pro',   29.99, 299, 20, 50, 0.50, 10, '{"discord_webhook": true, "telegram": true, "ai_advisor": true}', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- 2. payment_history — 付款紀錄
CREATE TABLE IF NOT EXISTS payment_history (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id                     VARCHAR(255)        NOT NULL,
    subscription_id             BIGINT,
    stripe_payment_intent_id    VARCHAR(255),
    amount                      DOUBLE PRECISION,
    currency                    VARCHAR(10)         DEFAULT 'USD',
    status                      VARCHAR(255),
    paid_at                     TIMESTAMP,
    created_at                  TIMESTAMP,
    CONSTRAINT pk_payment_history PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_ph_user_id ON payment_history (user_id);
CREATE INDEX IF NOT EXISTS idx_ph_stripe_pi ON payment_history (stripe_payment_intent_id);

-- 3. user_trade_settings — 個人交易參數（一人一列）
CREATE TABLE IF NOT EXISTS user_trade_settings (
    user_id                     VARCHAR(255)        NOT NULL,
    risk_percent                DOUBLE PRECISION,
    max_leverage                INTEGER,
    max_dca_layers              INTEGER,
    max_position_size_usdt      DOUBLE PRECISION,
    allowed_symbols             TEXT,
    auto_sl_enabled             BOOLEAN             DEFAULT true NOT NULL,
    auto_tp_enabled             BOOLEAN             DEFAULT true NOT NULL,
    created_at                  TIMESTAMP,
    updated_at                  TIMESTAMP,
    CONSTRAINT pk_user_trade_settings PRIMARY KEY (user_id),
    CONSTRAINT fk_uts_user_id FOREIGN KEY (user_id) REFERENCES users(user_id)
);

-- 4. signals — 訊號歷史
CREATE TABLE IF NOT EXISTS signals (
    signal_id                   VARCHAR(255)        NOT NULL,
    source_platform             VARCHAR(255),
    source_channel_id           VARCHAR(255),
    source_channel_name         VARCHAR(255),
    source_guild_id             VARCHAR(255),
    source_author_name          VARCHAR(255),
    source_message_id           VARCHAR(255),
    action                      VARCHAR(255),
    symbol                      VARCHAR(255),
    side                        VARCHAR(255),
    entry_price_low             DOUBLE PRECISION,
    entry_price_high            DOUBLE PRECISION,
    stop_loss                   DOUBLE PRECISION,
    take_profits                TEXT,
    leverage                    INTEGER,
    close_ratio                 DOUBLE PRECISION,
    new_stop_loss               DOUBLE PRECISION,
    new_take_profit             DOUBLE PRECISION,
    raw_message                 TEXT,
    signal_hash                 VARCHAR(255),
    execution_status            VARCHAR(255),
    rejection_reason            VARCHAR(255),
    trade_id                    VARCHAR(255),
    created_at                  TIMESTAMP,
    CONSTRAINT pk_signals PRIMARY KEY (signal_id)
);

CREATE INDEX IF NOT EXISTS idx_sig_symbol ON signals (symbol);
CREATE INDEX IF NOT EXISTS idx_sig_action ON signals (action);
CREATE INDEX IF NOT EXISTS idx_sig_signal_hash ON signals (signal_hash);
CREATE INDEX IF NOT EXISTS idx_sig_source_platform ON signals (source_platform);
CREATE INDEX IF NOT EXISTS idx_sig_created_at ON signals (created_at);
